### ISSUE TITLE
Completeness

### ISSUE THREAD

**Issue by nivekuil** [wfraser/fuse-mt#1]
How close is fuse-mt to being ready for prime-time? I see that there's already a working example, and the API seems like a straightforward layer over the rust-fuse crate. Is the path translation part already stable enough to be used over rust-fuse?

**Comment by wfraser** [comment]
Pretty close, but a few things need to be done still.

First and foremost,
- [ ] documentation!

A few remaining syscalls to implement:
- [ ] `access`
- [ ] `getlk`
- [ ] `setlk`
- [ ] `bmap`
- [ ] `setxattr`
- [ ] `removexattr`

Also:
- [ ] currently depends on a version of `rust-fuse` (with my xattr changes) that hasn't been included in a release yet.

Documentation is the big one obviously. However, as far as functionality goes, I think it's pretty stable, but having someone besides me exercising it would be nice. If it helps you, I could cut a release (0.1.0 or such, because I'm not ready to guarantee a 100% stable API yet) and put it on crates.io.

**Comment by wfraser** [comment]
I've made a v0.1.0 release, but until `rust-fuse` is updated on crates.io, I can't publish there, because they forbid specifying dependencies from non-crates.io sources.

**Comment by nivekuil** [comment]
Sounds good! I'd be happy to try a 0.1.0 release. Opened an issue in rust-fuse to get an updated version published.

**Comment by wfraser** [comment]
I've pushed v0.1.2 to https://crates.io/crates/fuse-mt

(0.1.2 is just 0.1.0 plus one bugfix, plus another version bump because I accidentally uploaded the experimental branch as 0.1.1... 😐 )

**Comment by wfraser** [comment]
I made some rough documentation (viewable at https://docs.rs/fuse_mt/), and I'm also working on adding some tests.

**Comment by cholcombe973** [comment]
I think I'm going to give this a spin also.  I'd like to rewrite the gluster fuse client in rust and that whole inode thing from rust-fuse is messing me up.  Thanks for implementing this!

**Comment by wfraser** [comment]
I'm going to mark this as closed, given that I now have documentation up, some public releases, and all but a few pretty uncommonly-used syscalls implemented. While somewhat experimental, this crate is definitely usable for actually making things work.

Definitely not done working on the project though, so not "complete" in that sense! 😄
