### ISSUE TITLE
Hardlinks seem to be broken

### ISSUE THREAD

**Issue by pedrocr** [wfraser/fuse-mt#23]
I'm trying to add hardlinks by implementing `link()` but that doesn't even ever get called. strace tells me `linkat()` is getting called and receiving `ENOENT` but I don't see that reaching my code at all. All I see are two calls to `getattr()` for the destination of the link which doesn't yet exist because `link()` hasn't yet been called. Symlinks work fine though.

**Comment by wfraser** [comment]
I took a look at your code, and the problem seems to be due to the fact that in your `getattr`, you're returning a `FileAttr` where the `nlink` field is zero. `nlink = 0` means it's been unlinked from the filesystem and only exists because someone still has it open, but that situation is impossible if you're in `getattr` -- you have to have a link pointing to it to get there. I assume that when the kernel then gets the `link` syscall, it thinks the target file is deleted, so it responds with `ENOENT` and never even calls FUSE.

If you change `nlink` to 1, then it works fine.

**Comment by wfraser** [comment]
Just for fun, here's the code in the Linux kernel that makes this happen:

`/* Make sure we don't allow creating hardlink to an unlinked file */`

https://github.com/torvalds/linux/blob/43f462f1c2e111d2882b48baeeff774ae42e7c56/fs/namei.c#L4215

**Comment by pedrocr** [comment]
Thanks! I had assumed you could `unlink()` and keep a handle and then `link()` it back to the filesystem but since `link()` only takes paths that's not possible.
