### ISSUE TITLE
It would be nice if serde support was added

### ISSUE THREAD

**Issue by pedrocr** [wfraser/fuse-mt#25]
I'm trying to use serde to make it easier to serialize a file metadata struct to disk. It would be nice if the `FileType` enum implemented `Serialize/Deserialize`. This can probably be done behind a feature flag so that not everyone needs to drag in serde even if they're not using it.

**Comment by pedrocr** [comment]
Added a rust-fuse issue for this:

https://github.com/zargony/rust-fuse/issues/100

**Comment by wfraser** [comment]
That's a filesystem implementation detail and doesn't belong in a general-purpose library like this.

**Comment by pedrocr** [comment]
This is actually a rust-fuse issue really since that enum is defined there but I'm curious why you think that. How to store the file type is definitely an implementation detail but having a simple way to implement `Serialize/Deserialize` for `FileType` can make the implementation much easier. It would at least avoid this kind of code:

https://github.com/pedrocr/syncer/commit/6664d7e5ae1f7de12c43b7b1865fbab5aa924bc0

**Comment by wfraser** [comment]
It's an implementation detail of how to store a type, and the library used for that is part of that detail. Even when using serde, there's still the choice of whether to derive the impl, or write it by hand.

Also, in my experience, the file type is usually represented simply as an integer (usually simply the libc `mode_t`) because it's a simple enum without any data, so why do you need something as heavy as serde to serialize that?

For example, this is how the example passthrough filesystem "serializes" the type: https://github.com/wfraser/fuse-mt/blob/6a1c8921fb949588363eb2b329149c230bcc8c8b/example/src/passthrough.rs#L25-L36

**Comment by pedrocr** [comment]
That does pretty much the same thing I've done by doing the conversion manually to my own mirror type. I could convert it to an integer instead but there would be no gain. And you can't do a manual serde implementation over a type defined in another crate. There are remote mirror implementations but they don't seem to work when you use complex types like `HashMap<_,FileType>`.
