### ISSUE TITLE
utimens_macos sets values for which there is no way to query

### ISSUE THREAD

**Issue by pedrocr** [wfraser/fuse-mt#27]
`FilesystemMT`includes utimens_macos which sets `chgtime` and `bkuptime` but since those are not included in `FileAttr` how can this API ever work? There doesn't seem to be any way to get to those attributes.

**Comment by wfraser** [comment]
With Fuse, there's a `getxtimes` call to query `chgtime` and `bkuptime`, which is feature-gated to be macOS-only. I haven't yet implemented `getxtimes` in fuse-mt because frankly I'm not a macOS user, and so it's super low priority to me to implement macOS-only features. If it's important to you, feel free to submit a pull request, or if I have some free time soon I might do it myself.

The reason for the asymmetry is because the way these are set in Fuse is not through a separate call, but through the omnibus `setattr` call which includes the arguments `chgtime` and `bkuptime` (and not feature gated) among a bunch of others, and one of the conveniences `fuse-mt` does is split the `setattr` call into a number of simpler ones, so I had to handle them somehow :)

**Comment by pedrocr** [comment]
Ah that explains it, thanks. I'm not an OSX user either but I got a user that was and he was kind enough to do a PR for these values. Apparently the OSX finder errors out if you don't implement it. That's why I opened the bug report as I couldn't figure out what these did.

By the way I got a first few releases of my filesystem out and it seems to be working great for my use case:

https://github.com/pedrocr/syncer

I've been mulling over a full read/write multi-master sync design that I may implement as well in the near future. It would have been hard to get this far without `fuse_mt` so thanks for the great crate.

**Comment by wfraser** [comment]
Actually this is easy enough, and I've got a macOS system handly; I'll just implement it right now. :)

**Comment by pedrocr** [comment]
Awesome, I'll add that when you do a release with it. Thanks

**Comment by pedrocr** [comment]
I see you've released it but it's behind a platform gate. It would be nice if the FilesystemMT trait included everything even on Linux. That way it's much easier to test if something is compiling fine at least. It can just never be called on Linux, that's fine.
