### ISSUE TITLE
Feature: Support iterators in readdir

### ISSUE THREAD

**Issue by amosonn** [wfraser/fuse-mt#5]
Given the usage of the current `Vec<DirectoryEntry>` the user provides, one could go with the more general `Box<IntoIterator<DirectoryEntry>>`, or perhaps a generic for the whole `FilesystemMT` trait, which is a bit uglier but probably better for runtime. This won't hurt users who use the current API; in fact, if `FilesystemMT` becomes generic, the default type could be `Vec<DirectoryEntry>`, and in the other case, the users only need to wrap their vector up; but it also allows lazy checking of the directory contents, as is enabled by the low-level API, without the hassel of tracking the position.

**Comment by wfraser** [comment]
Interesting idea! But low-ish priority, because (1) it would be an API breaking change, and (2) it's pretty rare to only partially enumerate a directory, so the performance gains would be minimal.

I'll consider this the next time the minor version needs to be bumped for something else. I'd prefer that it be a `Box<IntoIterator<...>>`, not making `FilesystemMT` generic because that would get to be a pain pretty quickly.

**Comment by amosonn** [comment]
I can draft a PR, if you think it will find use.
For performance you are probably right, however it might reduce memory usage if the directory is large, and in some cases it might be more natural to implement it as in iterator (`HashMap::keys` comes to mind); of course one can `collect` to match the current API.

**Comment by wfraser** [comment]
I thought some more about this, and really don't think I've ever seen code which only partially enumerates a directory, so I don't think there's any real benefit over using `Vec`.
